name: moniepoint_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  permission_handler: ^10.4.3
  logger: ^2.0.1
  cached_network_image:
  shimmer: ^3.0.0
  flash: ^3.0.5+1
  intl:
  image_picker: ^1.0.2
  after_layout: ^1.2.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  streaming_shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  injectable: ^2.3.0
  lottie:
  flutter_animate:
  persistent_bottom_nav_bar_v2: ^4.2.8
  countup: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/svg/icons/
    - assets/lottie/
    - assets/svg/icons/